FROM node:24.13.0 AS build

WORKDIR /app

COPY package.json ./
RUN npm install 

COPY . .

RUN npm run build
# build 하고나면 사라짐 아래 FROM부터 다시 시작

FROM nginx:1.28

COPY --from=build /app/dist /usr/share/nginx/html
COPY ./default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
