FROM python:3.12.9

WORKDIR /app

RUN pip install uv

COPY pyproject.toml uv.lock ./
RUN uv sync 

COPY . .

EXPOSE 8010

CMD ["uv", "run", "fastapi", "run", "--host", "0.0.0.0", "--port", "8010", "--reload"]