FROM uv:1

WORKDIR /app

COPY pyproject.toml uv.lock ./
RUN uv sync 

COPY . .

EXPOSE 8000

# CMD ["python3"]

# FROM uv:1

CMD ["uv", "run", "fastapi", "run", "--host", "0.0.0.0", "--port", "8000"]

